#!/usr/bin/env bash
#
# This sets up a runtime environment for larsoft.
#

type -t greadlink >& /dev/null || { echo "Environment is not correctly set up -- greadlink not available." >&2 ; return 1 ; }
declare local_scriptdir="$(dirname "$(greadlink -f "${BASH_SOURCE:-$0}")")"
[[ "${BASH_SOURCE[0]}" == "$0" ]] || SOURCECMD="source"
$SOURCECMD "${local_scriptdir}/setup" 'develop' "$@"
unset local_scriptdir

