#!/usr/bin/env bash
#
# This sets up a runtime environment for larsoft.
#

declare local_scriptdir="$(dirname "$(grealpath "${BASH_SOURCE:-$0}")")"
[[ "${BASH_SOURCE[0]}" == "$0" ]] || SOURCECMD="source"
$SOURCECMD "${local_scriptdir}/setup" 'prod' "$@"
unset local_scriptdir
