#!/bin/bash
#
# This sets up a runtime environment for larsoft.
#

declare local_scriptdir="$(dirname "$(readlink -f "${BASH_SOURCE:-$0}")")"
source "${local_scriptdir}/setup" 'runtime' "$@"
unset local_scriptdir
