#!/usr/bin/env bash
#
# This sets up a runtime environment for larsoft.
#

type -t grealpath >& /dev/null || { echo "Environment is not correctly set up -- grealpath not available." >&2 ; return 1 ; }
declare local_scriptdir="$(dirname "$(grealpath "${BASH_SOURCE:-$0}")")"
[[ "${BASH_SOURCE[0]}" == "$0" ]] || SOURCECMD="source"
$SOURCECMD "${local_scriptdir}/setup" 'runtime' "$@"
unset local_scriptdir
